spring.application.name=e-commerce

# Database configuration
spring.datasource.name=e-commerce-db
spring.datasource.url=jdbc:postgresql://ep-crimson-grass-a191z29d-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GeBF7jVzNXc0

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server.port=8080
server.servlet.context-path=/api

# Logging configuration
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG


# Harikiri configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000

